name: Publish Opera Add-on
description: GitHub action for publishing extensions to Opera Add-ons
author: fatidian1

inputs:
  package-id:
    description: Package ID (not required for verify action)
    required: false
  package-path:
    description: Path to .zip or .crx file (not required for verify action)
    required: false
  email:
    description: Email for Opera Developer account
    required: true
  password:
    description: Password for Opera Developer account
    required: true
  action:
    description: Action to perform (publish, upload or verify)
    required: true
    default: publish

runs:
  using: composite
  steps:
    - name: Populate .env file
      shell: bash
      run: |
        echo "OPERA_ADDON_PACKAGE_ID=${{ inputs.package-id }}" >> .env
        echo "OPERA_ADDON_PACKAGE_PATH=${{ inputs.package-path }}" >> .env
        echo "OPERA_ADDON_EMAIL=${{ inputs.email }}" >> .env
        echo "OPERA_ADDON_PASSWORD=${{ inputs.password }}" >> .env
        echo "OPERA_ADDON_ACTION=${{ inputs.action }}" >> .env
    - name: List files
      shell: bash
      run: ls -la
    - name: Show github workspace path
      shell: bash
      run: echo ${{ github.workspace }}
    - name: Show current path
      shell: bash
      run: pwd
    - name: Run puppeteer
      id: puppeteer-run
      uses: tj-actions/docker-run@v2
      with:
        image: ghcr.io/puppeteer/puppeteer:24.22.2
        name: opera-addon
        options: >-
          -v ${{ github.workspace }}:/workspace
          --workdir /workspace
          --user root
          -e NPM_CONFIG_CACHE=/workspace/.npm
          -e PUPPETEER_CACHE_DIR=/home/pptruser/.cache/puppeteer
          -e HOME=/workspace
        args: |
          npm ci --no-audit --no-fund
          node index.js

branding:
  icon: globe
  color: red
