name: Publish

permissions:
  contents: write
  discussions: write

on:
  push:
    tags:
      - '*'

jobs:
  github_release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
